### ISSUE TITLE
unable to build mongodb connector

### ISSUE THREAD

**Issue by zborisha** [Stratio/stratio-connector-mongodb#1]
I tried to build and install MongodB connector from Github (it would be great if there was one built already and available to be used with crossdata)

Documentation is not correct https://github.com/Stratio/stratio-connector-mongodb/blob/master/doc/src/site/sphinx/about.rst

This file talks about non-existent file that should be created during package target/stratio-connector-mongodb-[VERSION]/bin/stratio-connector-mongodb-core[VERSION] start

Managed to create rpm and tried to install it into running crossdata vagrant machine but for some reason it does not install correctly.

[root@crossdata vagrant]# rpm -i stratio-connector-mongodb-0.5.0_SNAPSHOT.noarch.rpm 
cp: cannot stat `/opt/sds/stratio-connector-mongodb/template/MongoDBConnector': No such file or directory
warning: %post(stratio-connector-mongodb-0.5.0-0.1.20150718.222944.noarch) scriptlet failed, exit status 1

Parts were installed but it looks like not everything. I tried to execute

[root@crossdata vagrant]# service stratio-connector-mongodb start
stratio-connector-mongodb: unrecognized service

It looks like documentation is wrong - the service name is connector-mongodb

[root@crossdata vagrant]#  service connector-mongodb start
env: /etc/init.d/connector-mongodb: Permission denied

After fixing permissions looks like this script is referencing file that does not exist

[root@crossdata init.d]#  service connector-mongodb start
/etc/init.d/connector-mongodb: line 1: /opt/sds/stratio-connector-mongodb/bin/stratio-connector-mongodb: No such file or directory
/etc/init.d/connector-mongodb: line 1: exec: /opt/sds/stratio-connector-mongodb/bin/stratio-connector-mongodb: cannot execute: No such file or directory

**Comment by pmadrigal** [comment]
We have troubles in some deb and rpm generation.

We are going to check it and solve it as soon as possible.

**Comment by josegom** [comment]
Hello,

We have fixed the release 0.4 documentation  https://github.com/Stratio/stratio-connector-mongodb/tree/branch-0.4. We have explained better how to compile and execute the connector.

Now we are working to improve the master branch documentation and rpm generation.

Thanks for the feedback.
